const GAMES = [
  {"img":"apt_i.jpg","title":"A Plague Tale: Innocence","sub":null},
  {"img":"a_way_out.jpg","title":"A Way Out","sub":null},
  {"img":"aoe4.jpg","title":"Age of Empires IV","sub":null},
  {"img":"alt_f4.jpg","title":"ALTF4","sub":null},  
  {"img":"arise_ass.jpeg","title":"Arise A Simple Story","sub":null},
  {"img":"acu.jpg","title":"Assassin's Creed: Unity","sub":null},
  {"img":"notre_dame.jpg","title":"Assassin's Creed: Unity","sub":"Notre Dame"},
  {"img":"asamu.jpg","title":"A Story About My Uncle","sub":null},
  {"img":"backrooms_escape_together.jpg","title":"Backrooms: Escape Together","sub":null},
  {"img":"bg3.jpeg","title":"Baldur's Gate 3","sub":null},
  {"img":"batman_asylum.jpg","title":"Batman: Arkham Asylum","sub":null},
  {"img":"batman_city.jpg","title":"Batman: Arkham City","sub":null},
  {"img":"batman_knight.jpg","title":"Batman™: Arkham Knight","sub":null},
  {"img":"batots.jpg","title":"Brothers: A Tale of Two Sons","sub":null},
  {"img":"bioshock_inf.jpg","title":"Bioshock","sub":"Infinite"},
  {"img":"blood_code.jpg","title":"Blood Code","sub":null},
  {"img":"cod_bo_cw.jpeg","title":"Call of Duty®: Black Ops Cold War","sub":null},
  {"img":"cod_iw.jpg","title":"Call of Duty: Infinite Warfare","sub":null},
  {"img":"cats_and_the_other_lives.jpg","title":"Cats and the Other Lives","sub":null},
  {"img":"chained_together.jpg","title":"Chained Together","sub":null},
  {"img":"contra.jpg","title":"Contra","sub":null},
  {"img":"cs2.jpg","title":"Counter-Strike 2","sub":null},
  {"img":"crysis.jpg","title":"Crysis","sub":null},
  {"img":"crysis2.jpg","title":"Crysis 2","sub":null},
  {"img":"crysis3.jpg","title":"Crysis 3","sub":null},
  {"img":"cube_escape_collection.jpeg","title":"Cube Escape Collection","sub":null},
  {"img":"cp77.jpg","title":"Cyberpunk 2077","sub":null},
  {"img":"dead_space3.jpg","title":"Dead Space 3","sub":null},
  {"img":"dear_esther.jpg","title":"Dear Esther","sub":"Landmark Edition"},
  {"img":"deathloop.jpg","title":"DEATHLOOP","sub":null},
  {"img":"dutm.jpg","title":"Deliver Us The Moon","sub":null},
  {"img":"detroit.jpg","title":"Detroit: Become Human","sub":null},
  {"img":"dmc4.jpg","title":"Devil May Cry 4","sub":null},
  {"img":"dmc5.jpg","title":"Devil May Cry 5","sub":null},
  {"img":"dsr.jpg","title":"Dark Souls","sub":"Remastered"},
  {"img":"ds3.jpg","title":"Dark Souls 3","sub":null},
  {"img":"death_stranding.jpg","title":"Death Stranding","sub":null},
  {"img":"dishonored.jpg","title":"Dishonored","sub":null},
  {"img":"doom_eternal.jpg","title":"DOOM Eternal","sub":null},
  {"img":"elden_ring.jpeg","title":"ELDEN RING","sub":null},
  {"img":"fallout4.jpg","title":"Fallout","sub":"4"},
  {"img":"fc_primal.jpg","title":"Far Cry Primal","sub":null},
  {"img":"far_lone_sails.jpg","title":"FAR: Lone Sails","sub":null},
  {"img":"finding_paradise.jpg","title":"Finding Paradise","sub":null},
  {"img":"fh4.jpg","title":"Forza Horizon","sub":"4"},
  {"img":"hudson_hornet.jpg","title":"Forza Horizon 4","sub":"Hudson Hornet"},
  {"img":"florence.jpg","title":"Florence","sub":null},
  {"img":"fh5.jpg","title":"Forza Horizon 5","sub":null},
  {"img":"ghostrunner.jpeg","title":"Ghostrunner","sub":null},
  {"img":"gow.jpg","title":"God of War","sub":null},
  {"img":"gow_ragnarok.jpg","title":"God of War Ragnarök","sub":null},
  {"img":"gris.jpg","title":"GRIS","sub":null},
  {"img":"hades.jpg","title":"Hades","sub":null},
  {"img":"heavy_rain.jpg","title":"Heavy Rain","sub":null},
  {"img":"hellblade_senuas_sacrifice.jpeg","title":"Hellblade: Senua's Sacrifice","sub":null},
  {"img":"high_on_life.jpeg","title":"High On Life","sub":null},
  {"img":"hff.jpg","title":"Human Fall Flat","sub":null},
  {"img":"hogwarts_legacy.jpeg","title":"Hogwarts Legacy","sub":null},
  {"img":"hzd.jpg","title":"Horizon Zero Dawn","sub":null},
  {"img":"hzd_fw.jpg","title":"Horizon Zero Dawn","sub":"Frozen Wilds"},
  {"img":"hollow_knight_silksong.jpg","title":"Hollow Knight: Silksong","sub":null},
  {"img":"immortals.jpg","title":"Immortals Fenyx Rising","sub":null},
  {"img":"immortals_a_new_god.jpg","title":"Immortals Fenyx Rising","sub":"A New God"},
  {"img":"injustice.jpg","title":"Injustice","sub":null},
  {"img":"inside.jpg","title":"Inside","sub":null},
  {"img":"it_takes_two.jpg","title":"It Takes Two","sub":null},
  {"img":"mortal_shell.jpeg","title":"Mortal Shell","sub":null},
  {"img":"tlou1.jpeg","title":"The Last of Us™ Part I","sub":null},
  {"img":"tlou2.jpg","title":"The Last of Us™ Part II","sub":"Remastered"},
  {"img":"jedi_fo.jpg","title":"STAR WARS Jedi: Fallen Order","sub":null},
  {"img":"jedi_survivor.jpg","title":"STAR WARS Jedi: Survivor","sub":null},
  {"img":"journey.jpg","title":"Journey","sub":null},
  {"img":"katana_zero.jpg","title":"Katana Zero","sub":null},
  {"img":"limbo.jpg","title":"Limbo","sub":null},
  {"img":"lis.jpg","title":"Life is Strange","sub":null},
  {"img":"little_nightmares.jpg","title":"Little Nightmares","sub":null},
  {"img":"little_nightmares_2.jpg","title":"Little Nightmares 2","sub":null},
  {"img":"mafia_def.jpg","title":"Mafia","sub":"Definitive Edition"},
  {"img":"mafia2.jpeg","title":"Mafia 2","sub":null},
  {"img":"metro_2033_redux.jpg","title":"Metro 2033 Redux","sub":null},
  {"img":"metro_lastlight_redux.jpg","title":"Metro: Last Light Redux","sub":null},
  {"img":"metro_exodus.jpg","title":"Metro Exodus","sub":null},
  {"img":"mimesis.jpg","title":"MIMESIS","sub":null},
  {"img":"mu_complex.jpg","title":"Mu Complex","sub":null},
  {"img":"spiderman.jpg","title":"Marvel's Spider-Man","sub":"Remastered"},
  {"img":"spiderman_mm.jpg","title":"Marvel's Spider-Man: Miles Morales","sub":null},
  {"img":"mbb.jpg","title":"Mount & Blade II: Bannerlord","sub":null},
  {"img":"ori_tbf.jpg","title":"Ori and the Blind Forest","sub":null},
  {"img":"ori_wow.jpg","title":"Ori and the Will of the Wisps","sub":null},
  {"img":"origin_prologue.jpg","title":"13:ORIGIN - Prologue","sub":null},
  {"img":"portal2.jpg","title":"Portal 2","sub":null},
  {"img":"portal_rtx.jpg","title":"Portal","sub":"RTX"},
  {"img":"prototype.jpg","title":"Prototype","sub":null},
  {"img":"prototype2.jpg","title":"Prototype 2","sub":null},
  {"img":"quantum_break.jpg","title":"Quantum Break","sub":null},
  {"img":"peak.jpg","title":"PEAK","sub":null},
  {"img":"planet_zoo.jpg","title":"Planet Zoo","sub":null},
  {"img":"raft.jpg","title":"Raft","sub":null},
  {"img":"rdr2.jpg","title":"Red Dead Redemption 2","sub":null},
  {"img":"rdo.jpg","title":"Red Dead Online","sub":null},
  {"img":"re2.jpg","title":"Resident Evil 2","sub":null},
  {"img":"re7.jpg","title":"Resident Evil 7 Biohazard","sub":null},
  {"img":"re_village.jpg","title":"Resident Evil Village","sub":null},
  {"img":"re_village_rose.jpg","title":"Resident Evil Village","sub":"Shadows of Rose"},
  {"img":"reaching_for_petals.jpg","title":"Reaching for Petals","sub":null},
  {"img":"sackboy.jpeg","title":"Sackboy™: A Big Adventure","sub":null},
  {"img":"sons_of_the_forest.jpeg","title":"Sons Of The Forest","sub":null},
  {"img":"rot_tr.jpg","title":"Rise of the Tomb Raider™","sub":null},
  {"img":"sot_tr.jpg","title":"Shadow of the Tomb Raider:","sub":"Definitive Edition"},
  {"img":"sekiro.jpg","title":"Sekiro: Shadows Die Twice","sub":null},
  {"img":"sifu.jpg","title":"Sifu","sub":null},
  {"img":"sts.jpg","title":"Slay the Spire","sub":null},
  {"img":"steelrising.jpg","title":"Steelrising","sub":null},
  {"img":"subnautica.jpg","title":"Subnautica","sub":null},
  {"img":"subnautica_bz.jpg","title":"Subnautica: Below Zero","sub":null},
  {"img":"superliminal.jpg","title":"Superliminal","sub":null},
  {"img":"supraland.jpg","title":"Supraland","sub":null},
  {"img":"supraland_siu.jpg","title":"Supraland Six Inches Under","sub":null},
  {"img":"tavern_manager_sim.jpg","title":"Tavern Manager Simulation","sub":null},
  {"img":"the_beginners_guide.jpg","title":"The Beginner's Guide","sub":null},
  {"img":"the_forest.jpg","title":"The Forest","sub":null},
  {"img":"tldoj.jpg","title":"The Last Day of June","sub":null},
  {"img":"the_swapper.jpg","title":"The Swapper","sub":null},
  {"img":"titanfall2.jpg","title":"Titanfall 2","sub":null},
  {"img":"twom.jpg","title":"This War of Mine","sub":null},
  {"img":"to_the_moon.jpg","title":"To the Moon","sub":null},
  {"img":"r6.jpg","title":"Tom Clancy's Rainbow Six Siege","sub":null},
  {"img":"tunic.jpg","title":"TUNIC","sub":null},
  {"img":"twelve_minutes.jpg","title":"Twelve Minutes","sub":null},
  {"img":"uncharted.jpg","title":"UNCHARTED™ 4: A Thief's End","sub":null},
  {"img":"uncharted_lost_legacy.jpeg","title":"UNCHARTED™: The Lost Legacy","sub":null},
  {"img":"unpacking.jpg","title":"Unpacking","sub":null},
  {"img":"viscera.jpg","title":"Viscera Cleanup Detail","sub":null},
  {"img":"wtpwa.jpg","title":"When The Past Was Around","sub":null},
  {"img":"witcher3.jpg","title":"Witcher 3","sub":null},
  {"img":"witcher3_kaermorhen.jpg","title":"Witcher 3","sub":"Kaer Morhen"},
  {"img":"witcher3_family.jpg","title":"Witcher 3","sub":"Family"},
  {"img":"witcher3_triss.jpg","title":"Witcher 3","sub":"Triss Merigold"},
  {"img":"witcher3_hos.jpg","title":"Witcher 3","sub":"Hearts of Stone"},
  {"img":"witcher3_bw.jpg","title":"Witcher 3","sub":"Blood and Wine"}
];